"""Catalogo cajas compras y conteos

Revision ID: f2b3409ac871
Revises: e1a59c0d35f4
"""
from alembic import op
import sqlalchemy as sa

revision = 'f2b3409ac871'
down_revision = 'e1a59c0d35f4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_empresa_id'), 'suppliers', ['empresa_id'], unique=False)
    op.create_table('cash_registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'name')
    )
    op.create_index(op.f('ix_cash_registers_empresa_id'), 'cash_registers', ['empresa_id'], unique=False)
    op.create_table('inventory_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('expected', sa.Integer(), nullable=False),
    sa.Column('counted', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'request_key')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'request_key')
    )
    op.create_index(op.f('ix_purchases_empresa_id'), 'purchases', ['empresa_id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('received', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id', 'product_id')
    )
    op.create_table('purchase_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.String(length=4000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'request_key')
    )
    with op.batch_alter_table('cash_movements') as batch:
        batch.add_column(sa.Column('actor_id', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('request_key', sa.String(length=100), nullable=True))
        batch.create_unique_constraint('uq_cash_movements_empresa_id_request_key', ['empresa_id', 'request_key'])
        batch.create_foreign_key('fk_cash_movements_actor_id', 'users', ['actor_id'], ['id'])
    with op.batch_alter_table('cash_sessions') as batch:
        batch.add_column(sa.Column('register_id', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('cashier_id', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('expected_on_close', sa.Numeric(precision=12, scale=2), nullable=True))
        batch.add_column(sa.Column('closed_by', sa.Integer(), nullable=True))
        batch.create_index('uq_open_cashier_branch', ['branch_id', 'cashier_id'], unique=True, sqlite_where=sa.text("status = 'open'"), postgresql_where=sa.text("status = 'open'"))
        batch.create_index('uq_open_register', ['register_id'], unique=True, sqlite_where=sa.text("status = 'open'"), postgresql_where=sa.text("status = 'open'"))
        batch.create_foreign_key('fk_cash_sessions_cashier_id', 'users', ['cashier_id'], ['id'])
        batch.create_foreign_key('fk_cash_sessions_closed_by', 'users', ['closed_by'], ['id'])
        batch.create_foreign_key('fk_cash_sessions_register_id', 'cash_registers', ['register_id'], ['id'])
    with op.batch_alter_table('products') as batch:
        batch.add_column(sa.Column('barcode', sa.String(length=80), nullable=True))
        batch.add_column(sa.Column('unit', sa.String(length=30), nullable=False, server_default='pieza'))
        batch.add_column(sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), nullable=False, server_default='0.16'))
        batch.add_column(sa.Column('tax_exempt', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch.add_column(sa.Column('price_includes_tax', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch.create_unique_constraint('uq_products_empresa_id_barcode', ['empresa_id', 'barcode'])
    with op.batch_alter_table('sale_items') as batch:
        batch.add_column(sa.Column('unit', sa.String(length=30), nullable=False, server_default='pieza'))
        batch.add_column(sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), nullable=False, server_default='0.16'))
        batch.add_column(sa.Column('tax_exempt', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch.add_column(sa.Column('price_includes_tax', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch.add_column(sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch.add_column(sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch.add_column(sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch.add_column(sa.Column('cost', sa.Numeric(precision=12, scale=4), nullable=False, server_default='0'))
    with op.batch_alter_table('sales') as batch:
        batch.add_column(sa.Column('folio', sa.String(length=60), nullable=True))
        batch.add_column(sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
        batch.add_column(sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch.add_column(sa.Column('discount_reason', sa.String(length=160), nullable=True))
        batch.add_column(sa.Column('discount_approved_by', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('actor_id', sa.Integer(), nullable=True))
        batch.create_unique_constraint('uq_sales_empresa_id_folio', ['empresa_id', 'folio'])
        batch.create_foreign_key('fk_sales_discount_approved_by', 'users', ['discount_approved_by'], ['id'])
        batch.create_foreign_key('fk_sales_actor_id', 'users', ['actor_id'], ['id'])
    with op.batch_alter_table('stock') as batch:
        batch.add_column(sa.Column('average_cost', sa.Numeric(precision=12, scale=4), nullable=False, server_default='0'))
    with op.batch_alter_table('stock_movements') as batch:
        batch.add_column(sa.Column('actor_id', sa.Integer(), nullable=True))
        batch.create_foreign_key('fk_stock_movements_actor_id', 'users', ['actor_id'], ['id'])
    db = op.get_bind()
    branches = db.execute(sa.text('SELECT id, empresa_id FROM branches')).fetchall()
    for branch_id, empresa_id in branches:
        db.execute(sa.text("INSERT INTO cash_registers (branch_id, empresa_id, name) VALUES (:branch, :empresa, 'Caja 1')"),
                   {'branch': branch_id, 'empresa': empresa_id})
        register_id = db.execute(sa.text('SELECT id FROM cash_registers WHERE branch_id = :branch'), {'branch': branch_id}).scalar()
        db.execute(sa.text('UPDATE cash_sessions SET register_id = :register WHERE branch_id = :branch'),
                   {'register': register_id, 'branch': branch_id})
    # Do not guess a legacy cashier. A manager closes old turns before reopening under an owner.
    for sale_id, branch_id in db.execute(sa.text('SELECT id, branch_id FROM sales')).fetchall():
        db.execute(sa.text('UPDATE sales SET folio = :folio WHERE id = :id'),
                   {'id': sale_id, 'folio': f'LI-B{branch_id}-{sale_id:08d}'})


def downgrade():
    raise RuntimeError('Esta migración incorpora nuevos registros de dinero e inventario. Restaura el respaldo y la versión anterior juntos para volver atrás.')
